# Generated by Django 4.1.2 on 2022-10-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
