# Generated by Django 4.1.2 on 2022-10-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='file_contant',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='votes',
        ),
    ]
