# Generated by Django 4.1.2 on 2022-10-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_file_contant_alter_menu_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='file_contant',
            field=models.FileField(null=True, upload_to='menus/'),
        ),
    ]
